version: 2
updates:
  - package-ecosystem: maven
    directory: "/spring-security-auth-server"
    schedule:
      interval: daily
      time: '05:00'
      timezone: Asia/Jakarta
    open-pull-requests-limit: 10

  - package-ecosystem: maven
    directory: "/spring-security-client"
    schedule:
      interval: daily
      time: '05:00'
      timezone: Asia/Jakarta
    open-pull-requests-limit: 10

    
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
